apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: k8-jenkins
spec:
  containers:
  - command: 
    - "cat"
    image: docker:24.0.2
    name: docker-agent
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "100m"
        memory: "100Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"
    tty: true
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
    - name: docker-sock
      mountPath: /var/run/docker.sock

  - command: 
    - "cat"
    image: "hadolint/hadolint:v2.12.0-alpine"
    name: "hadolint-agent"
    imagePullPolicy: "IfNotPresent"
    tty: true
    volumeMounts:
    - name: workspace-volume
      mountPath: /home/jenkins/agent
    - name: docker-sock
      mountPath: /var/run/docker.sock
      
  volumes:
  - name: workspace-volume
    emptyDir: {}
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"
  dnsPolicy: ClusterFirst