FROM openjdk:17.0.2-jdk
LABEL maintainer pgr
ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000

ARG MAVEN_VERSION=3.8.8
ARG USER_HOME_DIR="/home/${user}"

ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN groupadd -g ${gid} ${group} \
    && useradd -d "$USER_HOME_DIR" -u ${uid} -g ${gid} -m -s /bin/bash ${user}

RUN mkdir -p /usr/share/maven /user/share/maven/ref \
    && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
    && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
    && rm -f /tmp/apache-maven.tar.gz \
    && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

ENV TZ='Asia/kolkata'
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install build dependencies
RUN microdnf install yum 
RUN yum update -y
RUN yum install -y jq unzip git ruby findutils
RUN yum clean all
RUN microdnf clean all
RUN rm -rf /var/cache/yum

USER ${user}