@Library('pgr_automation_libraries') _  

def common =  new org.pgr.pipeline.utilities.common()

def gitrepoName = ""
def artifactoryURL = ""
def imageRepo = ""

def dockerFileTagMap = [
  ["./Dockerfile.24.0.6", "24.0.6"]
]

pipeline {
  agent {
    kubernetes {
      label 'k8-jenkins'
      defaultContainer 'jnlp'
      yaml kubernetesAgent("http://192.168.1.120:8070")
    }
  }
  stages {
    stage('Lint Dockerfile') {
      steps{
        container('hadolint-agent'){
          script{
            dockerFileTagMap.each {filename ->
            def dockerfile = filename(0)
            sh """
              echo "Running dockerLint for Dockerfile: ${dockerfile}"
              hadolint ${dockerfile} || true 
            """
            }
          }
        }
      }
    }
  }
  
}