FROM golang:1.21 AS builder

# Install dependencies and clone Trivy
RUN apt-get update && apt-get install -y git
RUN wget "https://get.trivy.dev/trivy?type=tar.gz&version=0.65.0&os=linux&arch=arm64" -O trivy.tar.gz && \
    tar -xzf trivy.tar.gz 

# Final image
FROM alpine:3.18

RUN apk --no-cache add ca-certificates

COPY --from=builder trivy /usr/local/bin/trivy

ENTRYPOINT ["trivy"]
